### ISSUE TITLE
Creation of CloudFormation stack fails as Autoscaling group does not get response from EC2 Instances.

### ISSUE THREAD

**Issue by manindravarma** [aws-quickstart/quickstart-datastax#12]
Hi,

When we are using these templates to create CloudFormation stack, the child stack "DC0stack" failed to create Autoscaling group with below error.
"Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement"

Looking at the Instance /var/log/cfn-init.log, I see that the exection stuck while processing "01_add_node" which is executed as part of the userdata in launch configuration and this is the reason why the instance is not sending cfn-signal back to autoscaling group. Please find the log snippet below.

---------
2018-10-17 16:52:09,556 [INFO] Command 01_setup_disk succeeded
2018-10-17 16:52:09,556 [DEBUG] Command 01_setup_disk output: mke2fs 1.42.13 (17-May-2015)
Creating filesystem with 268435456 4k blocks and 67108864 inodes
Filesystem UUID: 818ffc17-ccff-46ed-9793-9a1ae299aa05
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
	102400000, 214990848

Allocating group tables:    0/8192         done                            
Writing inode tables:    0/8192         done                            
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information:    0/8192         done

2018-10-17 16:52:09,556 [DEBUG] No services specified
2018-10-17 16:52:09,557 [INFO] Running config add_node
2018-10-17 16:52:09,558 [DEBUG] No packages specified
2018-10-17 16:52:09,558 [DEBUG] No groups specified
2018-10-17 16:52:09,558 [DEBUG] No users specified
2018-10-17 16:52:09,558 [DEBUG] No sources specified
2018-10-17 16:52:09,558 [DEBUG] No files specified
2018-10-17 16:52:09,558 [DEBUG] Running command 01_add_node
2018-10-17 16:52:09,558 [DEBUG] No test for command 01_add_node
---------

I have tried to recreate the stack multiple times but the stack always fails at the same step.

Please help me find a solution for this issue.

**Comment by scotthds** [comment]
Auto scaling is not part of the quickstart and is not recommended for DSE production deployments. If new nodes are to be added to a cluster, it is recommended they be added at scheduled times to avoid cluster latency b/c of streaming data or compaction that can happened when new nodes come into play.
