### ISSUE TITLE
Autoscaling group with below error 

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-datastax#13]
failing while creating Autoscaling group with below error 
"Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement" 

I have tested the solution in my account and also faced same issue. On further troubleshooting I found that the EC2 instances are not sending cfn-signal back to Autoscaling group. Looking at the /var/log/cfn-init.log file, I observed that the userdata execution got stuck while executing "01_add_node" command. 

I tried to manually run "01_add_node" command on the instance and found that there were multiple issues with the script. I observed that the script is trying to download lcm.pem.pub which is not present in respective S3 bucket. I then found that the file is already been deleted from S3 by another child stack which created the file. Once I fixed this the script got stuck while trying to metadata information which I couldnt solve it further.

**Comment by avattathil** [comment]
@scotthds please provide guidance

**Comment by scotthds** [comment]
Auto scaling is not part of the Quickstart and is not recommended for DSE production deployments. If new nodes are to be added to a cluster, it is recommended they be added at scheduled times to avoid cluster latency b/c of streaming data or compaction that can happened when new nodes come into play.

**Comment by manindravarma** [comment]
https://github.com/aws-quickstart/quickstart-datastax/blob/master/templates/datacenter.template

The above template which is part of QuickStart have Autoscaling group included. So QuickStart itself is creating the Autoscaling group. Can you please take a look at the above template and comment on Autoscaling group creation.

**Comment by MightyPixel** [comment]
I hit the same issue as @avattathil described. The default configuration creates a autoscaling group. The instances are successfully created and are Healthy. However the userdata can't be executed because it fails on the  "/usr/local/bin/cfn-init" command. I'm not sure how to proceed. Could someone advice?

**Comment by MightyPixel** [comment]
I also logged into one of the nodes and tried to run the cfn-init command by hand. Here is the output:
```
root@ip-10-0-46-104:~# /usr/local/bin/cfn-init -v          --stack arn:aws:cloudformation:us-east-2:<id>:stack/DSE-DC0stack-<id>/<uuid>         --resource CassandraLaunchConfig          --configsets full_install          --region us-east-2
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 70: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 70: ordinal not in range(128)
Logged from file util.py, line 476
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 884, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 70: ordinal not in range(128)
Logged from file util.py, line 476
^CTraceback (most recent call last):
  File "/usr/local/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 108, in apply
    commandResult = LoggingProcessHelper(cmd_to_run, name=u'Command %s' % name, env=env, cwd=cwd).call()
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 470, in call
    results = self.process_helper.call()
  File "/usr/local/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 456, in call
    returnData = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
```
Then I tried adding export LC_CTYPE=en_US.UTF-8 to the ~/.bashrc as suggested for this error. It did not help.
I also tried changing the default python to python3 and that also did not help.
The nodes use the `ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190204.3 (ami-0800e99ee8301b917)` AMI.
