### ISSUE TITLE
Parameter passing bug in `quickstart-datastax-no-vpc.template`

### ISSUE THREAD

**Issue by cpoczatek** [aws-quickstart/quickstart-datastax#2]
Commit `d3a09aa` introduced a bug in how the `DCSizes` param is passed to `opscenter.template`, should have been:
```
"DCSizes": {
   "Fn::Join": [",", {
       "Ref": "DCSizes"
   }]
}
```
Fixed in develop branch, issue can be closed on merge to master.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-datastax/commit/77d488d928564d380856cc4732cae0679ccf2e03
