### ISSUE TITLE
Missing Mapping

### ISSUE THREAD

**Issue by mtruiz81** [aws-quickstart/quickstart-datastax#6]
hi,

when using quickstart-datastax-no-vpc.template in Franckurt Region I am getting this error:
Template error: Unable to get mapping for AWSAMIRegionMap::eu-central-1:US1604HVM

I guess that mapping is missing in the AWSAMIRegionMAP, nevertheless I can see AMI exist in that region.

how I can fix this issue?

Thanks

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-datastax/commit/5bc82e8008137f36b15f5deb0b84762586eb4ba4
