### ISSUE TITLE
Key Name parameter can't detect actual available environment keys

### ISSUE THREAD

**Issue by jokerbea** [aws-quickstart/quickstart-datastax#8]
I'm trying to setup DataStax with the new VPC cloudformation template script and it doesn't recognize any of the key names in the environment, and also doesn't allow to manually type it.
Is there a work around this?

**Comment by avattathil** [comment]
Cannot replicate. Just loaded the New VPC [template](https://fwd.aws/mR5pP) and it did not exhibit the symptoms described.  Key Name selectable from the drop down as expected (Screenshot Attached) 

![image](https://user-images.githubusercontent.com/5912128/44428107-3d54dc00-a548-11e8-9ab6-eeab0051af21.png)
