### ISSUE TITLE
	Template error: Fn::Select cannot select nonexistent value at index 2

### ISSUE THREAD

**Issue by jokerbea** [aws-quickstart/quickstart-datastax#9]
It seems like it cannot create the VPC either
Client Request Token:Console-CreateStack-d8b0e7aa-bc0e-4c2d-975a-0286a91a0a8d
--

**Comment by jokerbea** [comment]
![image](https://user-images.githubusercontent.com/12341211/44055610-e9775e08-9f13-11e8-9bc1-5e64bb67379e.png)

**Comment by avattathil** [comment]
This happens when you don't pass the correct number of AZs or try to launch into a region that only has 2 AZ's please retry with 3 AZ 
See screenshot for example 
![image](https://user-images.githubusercontent.com/5912128/44427770-4ee9b400-a547-11e8-891a-e4d68eecf153.png)

**Comment by nickyfoto** [comment]
I have the same problem when try to use the template https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2018-08-30/amazon-eks-vpc-sample.yaml at us-east-1. I didn't see the VPC Network Configuration using this template using cloudformation. I successfully created the vpc at us-west-2. But still don't know why I cannot do the same at us-east-1.
